const dialog=document.querySelector('#record-dialog');
const content=document.querySelector('#dialog-content');
let reportAdded=false;
const rows=(items)=>'<dl>'+items.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')+'</dl>';
const records={
overview:()=>({k:'An illustrative journey',title:'Meet batch FLM–024.',body:'Follow one illustrative waste-to-product path: used packaging, recovered granules, then clean industrial film. The residue branch stays visible too. Other materials follow different paths.',rows:[['Material','Used flexible packaging film'],['Journey','Waste → granules → industrial film'],['Evidence','Sample records, not verified']],action:'<button class="cta" data-jump="collection">Begin the journey <span>↓</span></button>'}),
collection:()=>({k:'01 / Pickup before sorting',title:'The first link.',body:'A pickup record connects the material leaving a site to this batch. The sample includes a collection note and an outgoing weight entry.',rows:[['Batch','FLM–024'],['Collection date','08 Sep 2026 · sample'],['Material','Mixed used flexible film'],['Evidence','Pickup note + weight entry'],['Next holder','Sample sorting facility']],action:'<button class="cta" data-record="sorting">Inspect sorting <span>↓</span></button>'}),
sorting:()=>({k:'01 / Sorted waste',title:reportAdded?'The gap is visible. So is the update.':'One handoff. One evidence gap.',body:reportAdded?'A demonstration sorting report is now attached in this page session. Adding a record does not verify its contents.':'The receiving note connects this handoff to FLM–024. Without the sorting report, the material assessment is incomplete.',rows:[['Received','09 Sep 2026 · sample'],['Custody note','Present · illustrative'],['Sorting report',reportAdded?'Added · demonstration only':'Missing'],['Verification','Not independently verified']],action:reportAdded?'<div class="dialog-actions"><button class="cta" data-jump="sorting">Continue to recycling <span>↓</span></button><button class="text-button" id="reset-report">Reset sample</button></div>':'<button class="cta" id="add-report">Add demonstration report <span>+</span></button><span class="record-status">No file is uploaded or sent.</span>'}),
recycling:()=>({k:'02 / Recycling',title:'Follow the process.',body:'This illustrative mechanical route shreds and washes suitable sorted flexible packaging before reprocessing the recovered polymer. A process record links the input batch to its outputs.',rows:[['Input','Sorted flexible packaging · FLM–024'],['Sample route','Shredding, washing, reprocessing'],['Record','Present · illustrative'],['Outputs','Recovered polymer + residue']],action:'<button class="cta" data-jump="processing">Follow the granules <span>↓</span></button><p>Shown equipment is illustrative, not evidence of a real processing event.</p>'}),
recovered:()=>({k:'03 / Recycled granules',title:'Material, with a next step.',body:'In this example, the suitable fraction is cleaned and processed into granules. A later conversion step makes industrial film. Processing and conversion records connect the product to this batch.',rows:[['Input','Sorted flexible film fraction'],['Sample process','Washing + mechanical reprocessing'],['Output','Recovered plastic granules'],['Sample next step','Conversion into industrial film']],action:'<p>Not every flexible film is suitable for this process. This example makes no food-contact claim.</p><button class="text-button" data-record="residue">Follow the residue too <span>↗</span></button>'}),
residue:()=>({k:'03 / Residue',title:'The part that remains.',body:'Contamination and unsuitable fractions are separated as residue. Keeping that branch visible is part of following the whole batch.',rows:[['Fraction','Not recovered in this process'],['Evidence','Sample residue record'],['Treatment destination','Not established in this sample'],['Receiving evidence','Needed']],action:'<p>A processing record alone does not establish where the residue ultimately went.</p>'}),
destination:()=>({k:'04 / Recycled film',title:'A clean product. A traceable path.',body:'This illustrative route converts suitable recovered granules into clean industrial film. The conversion and dispatch notes link the new product to FLM–024. Receiving confirmation remains pending.',rows:[['Finished product','Clean industrial film · example'],['Conversion record','Present · illustrative'],['Dispatch note','Present · illustrative'],['Receiving confirmation','Pending']],action:'<p>The residue branch has its own destination evidence gap. Both need to stay visible.</p><button class="text-button" data-record="residue">Inspect residue destination <span>↗</span></button>'}),
start:()=>({k:'Start with one material journey',title:'What would your first batch need?',body:'Start with the material and its pickup record. Connect each receiving party, the process and both output paths as evidence becomes available.',rows:[['01','Material + pickup record'],['02','Handoff + sorting evidence'],['03','Recovered output + residue'],['04','Destination + receiving evidence']],action:'<button class="cta" data-jump="collection">Replay the sample <span>↺</span></button><p>This mock does not create a real batch or submit business information.</p>'})};
function openRecord(key){if(!Object.hasOwn(records,key))throw Error('Unknown record');if(key==='overview'){dialog.close();const network=document.querySelector('#network');network.scrollIntoView({behavior:document.documentElement.classList.contains('motion-paused')?'instant':'smooth'});network.focus({preventScroll:true});return {record:key,sample:true,reportAdded};}const r=records[key]();content.innerHTML=`<span class="dialog-kicker">${r.k}</span><h2 id="dialog-title">${r.title}</h2><p>${r.body}</p>${rows(r.rows)}${r.action||''}`;if(!dialog.open)dialog.showModal();else document.querySelector('#close-dialog').focus();return {record:key,sample:true,reportAdded};}
function setReport(added){reportAdded=added;const badge=document.querySelector('#evidence-badge');badge.innerHTML=added?'<span>✓</span> Demo report added':'<span>!</span> Sorting report needed';badge.classList.toggle('complete',added);document.querySelector('#sorting-summary').innerHTML=added?'A demonstration report is attached.<br>Its contents remain unverified.':'The receiving note is here.<br>The sorting report is still missing.';document.querySelector('#status').textContent=added?'Demonstration sorting report added. Not verified.':'Sample sorting report reset to missing.';openRecord('sorting');return {sample:true,reportAdded};}
document.addEventListener('click',e=>{const record=e.target.closest('[data-record]');if(record)openRecord(record.dataset.record);const jump=e.target.closest('[data-jump]');if(jump){dialog.close();document.getElementById(jump.dataset.jump).scrollIntoView({behavior:reduced.matches||paused?'instant':'smooth'});}if(e.target.closest('#add-report'))setReport(true);if(e.target.closest('#reset-report'))setReport(false);});
document.querySelector('#close-dialog').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;const motionButton=document.querySelector('#motion-toggle');function applyMotion(){document.documentElement.classList.toggle('motion-paused',paused);motionButton.textContent=paused?'Resume motion':'Pause motion';motionButton.setAttribute('aria-pressed',String(paused));}applyMotion();motionButton.onclick=()=>{paused=!paused;applyMotion();};
const sections=[...document.querySelectorAll('[data-stage]')],nav=[...document.querySelectorAll('.stage-nav a')],scenes=[...document.querySelectorAll('[data-scene]')],trace=document.querySelector('#trace-live');const length=trace.getTotalLength();trace.style.strokeDasharray=length;let ticking=false,lastStage=null;function update(){const progress=Math.min(1,Math.max(0,(scrollY+innerHeight*.45)/(document.documentElement.scrollHeight-innerHeight*.4)));trace.style.strokeDashoffset=length*(1-progress);let active=-1;sections.forEach((s,i)=>{if(s.getBoundingClientRect().top<innerHeight*.35)active=i;});if(active!==lastStage){scenes.forEach(scene=>scene.classList.toggle('is-active',scene.dataset.scene===(active===-1?'hero':String(active))));nav.forEach((a,i)=>{a.classList.toggle('active',i===active);if(i===active)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current');});document.documentElement.dataset.activeStage=String(active);lastStage=active;}ticking=false;}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(update);ticking=true;}},{passive:true});addEventListener('resize',update);addEventListener('pageshow',update);addEventListener('load',update);addEventListener('hashchange',()=>requestAnimationFrame(update));update();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_sample_evidence',description:'Open an illustrative FLM-024 evidence record on the page.',inputSchema:{type:'object',properties:{record:{type:'string',enum:Object.keys(records)}},required:['record'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.record!=='string'||Object.keys(input).length!==1)throw Error('Expected one record name');return openRecord(input.record);}})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'add_demonstration_sorting_report',description:'Attach a demonstration sorting report in this page session only. Does not submit or verify a real record.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||Object.keys(input).length)throw Error('No parameters expected');return setReport(true);}})).catch(()=>{});}catch{}}



reduced.addEventListener('change',e=>{paused=e.matches;applyMotion();});
const networkObserver=new IntersectionObserver(entries=>{entries.forEach(e=>document.documentElement.classList.toggle('in-network',e.isIntersecting));},{threshold:.05});networkObserver.observe(document.querySelector('#network'));

