/* Sample relationships, not real organisations or verified production records. */
(()=>{
const nodes=[
 {id:'source',x:110,y:255,kind:'material',size:112,label:'Sorted film bales',sub:'SOURCE MATERIAL',image:'collection-waste.webp?v=bales',record:'sorting',title:'Where the story starts.',body:'Used flexible packaging is assigned to batch FLM–024 at a sample sorting facility. The receiving note connects the handoff. The sorting assessment is still missing.',status:'Sorting report needed',pending:true},
 {id:'recycle',x:350,y:200,kind:'process',size:82,label:'Recycling',sub:'MECHANICAL PROCESS',image:'recycling.webp?v=iot',record:'recycling',title:'One input. Two paths.',body:'The sample mechanical process connects sorted packaging to recovered polymer. Unsuitable material leaves through a separate residue route.',status:'Sample process record present'},
 {id:'granules',x:530,y:290,kind:'material',size:96,label:'Granules',sub:'RECOVERED POLYMER',image:'granules.webp',record:'recovered',title:'Material with a next life.',body:'Recovered polymer becomes granules. Their link to the processing record preserves the origin of the material before conversion.',status:'Sample output record present'},
 {id:'convert',x:680,y:415,kind:'event',size:26,label:'Film conversion',sub:'TRANSFORMATION',record:'destination',title:'The shape changes.',body:'Suitable recovered granules are converted into industrial film. The conversion record connects the input material to the finished product.',status:'Sample conversion record present'},
 {id:'film',x:835,y:250,kind:'product',size:174,label:'Recycled film',sub:'PRODUCT / FLM–024',image:'clean-film.webp?v=haze',record:'destination',title:'A product. With its past attached.',body:'Clean industrial film is the outcome of this illustrative route. Follow its connections to see the material, process and records behind it.',status:'Receiving confirmation pending',pending:true},
 {id:'residue',x:350,y:475,kind:'residue',size:28,label:'Residue',sub:'SEPARATE OUTPUT',record:'residue',title:'The branch we cannot leave out.',body:'Contamination and unsuitable fractions are separated during recycling. The sample does not establish a treatment destination or receiving confirmation.',status:'Destination not established',pending:true},
 {id:'sorting_report',x:110,y:65,kind:'record',size:24,label:'Sorting report',sub:'MISSING',record:'sorting',title:'An open evidence gap.',body:'A receiving note identifies the handoff, but the material assessment is incomplete without a sorting report. A demo report may be attached for this page visit.',status:'Evidence needed',pending:true},
 {id:'processor',x:355,y:55,kind:'role',size:20,label:'Processor',sub:'SAMPLE ROLE',record:'recycling',title:'Who performs the process?',body:'This role represents the facility performing the sample recycling step. No real company or independently verified facility is identified here.',status:'Participant identity illustrative'},
 {id:'converter',x:680,y:560,kind:'role',size:20,label:'Converter',sub:'SAMPLE ROLE',record:'destination',title:'Who makes the film?',body:'The converter role represents the party turning recovered granules into film. This is a sample role, not an identified or certified company.',status:'Participant identity illustrative'},
 {id:'dispatch',x:920,y:475,kind:'record',size:24,label:'Dispatch note',sub:'SAMPLE RECORD',record:'destination',title:'A dispatch is one part of a handoff.',body:'The illustrative dispatch note links the finished product to its outgoing handoff. It does not establish receipt by the next holder.',status:'Sample dispatch record present'},
 {id:'receipt',x:820,y:60,kind:'record',size:24,label:'Receiving confirmation',sub:'PENDING',record:'destination',title:'The next link is still open.',body:'The product has a sample dispatch record. Confirmation from the receiving party remains pending, so the handoff is not presented as complete.',status:'Receiving evidence needed',pending:true}
];
const edges=[
 ['source','recycle','material','M166 255 C230 255 252 200 309 200'],
 ['recycle','granules','material','M391 200 C453 200 438 290 482 290'],
 ['granules','convert','material','M578 290 C644 290 615 415 667 415'],
 ['convert','film','material','M693 415 C768 415 710 310 767 295'],
 ['recycle','residue','branch','M350 241 C350 330 294 400 350 461'],
 ['source','sorting_report','evidence','M110 199 C110 155 110 127 110 89'],
 ['recycle','processor','custody','M350 159 C350 130 355 100 355 75'],
 ['convert','converter','custody','M680 428 C680 468 680 514 680 540'],
 ['film','dispatch','evidence','M892 315 C943 358 920 404 920 451'],
 ['film','receipt','evidence','M835 163 C835 130 820 110 820 84']
];
const root=document.querySelector('#network');
root.innerHTML=`<div class="network-intro"><div><p class="eyebrow">05 / THE CONNECTIONS BEHIND THE PRODUCT</p><h2>The film is new.<br><em>Its story isn’t.</em></h2></div><p>Material changes hands and form.<br>Its connections should stay visible.</p></div><div class="network-bar"><span>FLM–024 <small>ILLUSTRATIVE NETWORK</small></span><div><button id="network-reset">Full network</button><button id="network-motion" aria-pressed="false">Pause flow</button></div></div><div class="network-workspace"><div class="network-stage"><div class="network-graph" aria-label="Interactive product traceability network"><svg class="network-routes" viewBox="0 0 1040 640" aria-hidden="true"><defs><marker id="route-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="none" stroke="#a8ce88"/></marker></defs>${edges.map(([a,b,type,d])=>`<g data-edge="${a}:${b}" class="network-edge ${type}"><path d="${d}" class="route-line" ${type==='material'?'marker-end="url(#route-arrow)"':''}/>${type==='material'||type==='branch'?`<path d="${d}" pathLength="100" class="route-pulse"/>`:''}</g>`).join('')}</svg>${nodes.map(n=>`<button class="net-node net-${n.kind} ${n.pending?'is-pending':''}" style="--x:${n.x/10.4}%;--y:${n.y/6.4}%;--size:${n.size}px" data-node="${n.id}" aria-pressed="false" aria-controls="network-inspector"><span class="net-anchor">${n.image?`<img src="${n.image}" alt=""/>`:n.kind==='record'?'<span class="record-glyph" aria-hidden="true"></span>':n.kind==='role'?'<span class="role-glyph" aria-hidden="true"></span>':'<span class="event-glyph" aria-hidden="true"></span>'}</span><span class="net-label">${n.label}</span><span class="net-sub">${n.sub}</span></button>`).join('')}</div><div class="network-legend"><span><i></i>Material flow</span><span><i></i>Participant</span><span><i></i>Evidence</span><span class="amber">Open evidence gap</span></div></div><aside id="network-inspector" class="network-inspector" aria-live="polite" aria-atomic="true"></aside></div><details class="network-linear"><summary>Explore as a step-by-step list</summary><ol>${nodes.map(n=>`<li><button data-select="${n.id}">${n.label}</button><span>${n.pending?n.status:n.sub}</span></li>`).join('')}</ol></details><p class="network-note">Illustrative route and records. Participant roles are examples; no real company, verified claim or measured quantity is represented.</p>`;
const graph=root.querySelector('.network-graph'),inspector=root.querySelector('#network-inspector');
const mobilePaths=['M24 13 C24 19 32 19 32 25','M32 33 C32 38 25 39 25 44.5','M25 53.5 C25 59 35 58 35 63','M35 65 C35 69 36 72 36 77','M41 29 C72 29 79 32 79 41.5','M36 8 C53 8 57 5 74 5','M41 29 C58 29 59 24 75 24','M38 64 C56 64 62 63 76 63','M53 88 C71 88 65 94 79 94','M53 82 C65 82 66 79 79 79'];
graph.insertAdjacentHTML('afterbegin',`<svg class="network-mobile-routes" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${edges.map(([a,b,type],i)=>`<g data-edge="${a}:${b}" class="network-edge ${type}"><path d="${mobilePaths[i]}" class="route-line"/>${type==='material'||type==='branch'?`<path d="${mobilePaths[i]}" pathLength="100" class="route-pulse"/>`:''}</g>`).join('')}</svg>`);
let current='film';
function select(id,all=false){const n=nodes.find(n=>n.id===id);if(!n)return;current=id;
 let active=new Set([id]);const material=edges.filter(e=>e[2]==='material'||e[2]==='branch');
 if(['source','recycle','granules','convert','film','residue'].includes(id)){
 const before=new Set([id]),after=new Set([id]);for(let i=0;i<nodes.length;i++)material.forEach(([a,b])=>{if(before.has(b))before.add(a);if(after.has(a))after.add(b);});active=new Set([...before,...after]);edges.forEach(([a,b,t])=>{if(active.has(a)&&!['material','branch'].includes(t))active.add(b);});
 }else{const parent=edges.find(e=>e[1]===id)?.[0];if(parent){active.add(parent);for(let i=0;i<nodes.length;i++)material.forEach(([a,b])=>{if(active.has(b))active.add(a);});}}
 if(all)active=new Set(nodes.map(n=>n.id));
 root.querySelectorAll('[data-node]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.node===id));b.classList.toggle('muted-node',!active.has(b.dataset.node));});
 root.querySelectorAll('[data-edge]').forEach(g=>{const [a,b]=g.dataset.edge.split(':');g.classList.toggle('muted-edge',!active.has(a)||!active.has(b));});
 root.querySelector('#network-reset').classList.toggle('is-active',all);
 inspector.innerHTML=`<div class="inspector-kicker">${n.kind==='product'?'FINISHED PRODUCT':n.kind.toUpperCase()} <span>FLM–024</span></div><h3>${n.title}</h3><p>${n.body}</p><div class="inspector-status ${n.pending?'pending':''}"><span>${n.pending?'○':'—'}</span>${id==='sorting_report'&&reportAdded?'Demonstration report added · unverified':n.status}</div><button class="text-button" data-record="${n.record}">Inspect sample record <span>↗</span></button><div class="inspector-context"><span>CONNECTED TO</span>${edges.filter(e=>e[0]===id||e[1]===id).map(e=>{const other=nodes.find(n=>n.id===(e[0]===id?e[1]:e[0]));return `<button data-select="${other.id}">${other.label}<b>↗</b></button>`;}).join('')}</div>`;
}
root.addEventListener('click',e=>{const node=e.target.closest('[data-node]'),link=e.target.closest('[data-select]');if(node||link){select(node?node.dataset.node:link.dataset.select);if(matchMedia('(max-width:700px)').matches)inspector.scrollIntoView({behavior:document.documentElement.classList.contains('motion-paused')?'instant':'smooth',block:'center'});}if(e.target.closest('#network-reset'))select('film',true);});
graph.addEventListener('keydown',e=>{if(!e.target.closest('[data-node]')||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();let i=nodes.findIndex(n=>n.id===current);i=e.key==='Home'?0:e.key==='End'?nodes.length-1:(i+(['ArrowLeft','ArrowUp'].includes(e.key)?nodes.length-1:1))%nodes.length;select(nodes[i].id);root.querySelector(`[data-node="${nodes[i].id}"]`).focus();});
root.querySelector('#network-motion').onclick=()=>document.querySelector('#motion-toggle').click();
const sync=()=>{const p=document.documentElement.classList.contains('motion-paused');const b=root.querySelector('#network-motion');b.textContent=p?'Resume flow':'Pause flow';b.setAttribute('aria-pressed',String(p));};new MutationObserver(sync).observe(document.documentElement,{attributes:true,attributeFilter:['class']});sync();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){root.classList.add('network-revealed');observer.disconnect();}}),{threshold:.15});observer.observe(root);
select('film',true);
window.productNetwork={nodes,select,root};
})();





